name: Pre-merge checks and tests

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt install catch2 meson
      - uses: actions/checkout@v4
      - run: |
          meson setup build -Dwerror=true
          cd build
          meson compile
          ./test_reversi
